# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the container
COPY backend/package*.json ./

# Install server dependencies
RUN npm install

# Copy the server application source code to the container
COPY backend/ ./

# Expose the port the server runs on (e.g., 8080)
EXPOSE 8080

# Start the server application
CMD ["node", "server"]
