# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app/client

# Copy package.json and package-lock.json to the container
COPY client/package*.json ./

# Install client dependencies
RUN npm install

# Copy the client application source code to the container
COPY client/ ./

# Expose the port the client runs on (e.g., 3000)
EXPOSE 3000

# Start the client application
CMD ["npm", "start"]
